name: Sentinel

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:

jobs:
  run-test:
    name: run-test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: ["julienpeloton/fink-ci:latest"]

    container:
      image: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up env [1/2]
      run: |
        echo "FINK_FAT=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
        echo "${BINPATH}" >> $GITHUB_PATH

    - name: Set up env [2/2]
      run: |
        echo "PYTHONPATH="${PYTHONPATH}:${SPARKLIB}:${FINK_FAT}"" >> $GITHUB_ENV

    - name: Install Orbfit
      run: |
        dnf -y install epel-release
        dnf -y install aria2
        dnf -y install make-1:4.3-8.el9.x86_64
        dnf -y install gcc-gfortran
        mkdir /home/libs/OrbFit
        source ./script/orbFit_installer.sh --install_path /home/libs/OrbFit
        echo "/home/libs/OrbFit" >> $GITHUB_PATH

    - name: Check env
      run: |
        echo "FINK_FAT: $FINK_FAT"
        echo "SPARK_HOME: $SPARK_HOME"
        echo "SPARKLIB: $SPARKLIB"
        echo "PYTHONPATH: $PYTHONPATH"
        echo "JAVA_HOME: $JAVA_HOME"
        echo `python -V`

    - name: Run test suites
      run: |
        ./run_test.sh
        curl -s https://codecov.io/bash | bash
